MCU = atmega32
F_CPU = 8000000UL
CC = avr-gcc
OBJCOPY = avr-objcopy
CFLAGS = -mmcu=$(MCU) -DF_CPU=$(F_CPU) -Os -I. -Wall 
DEPFLAGS = -MMD -MP

SRC_DIR = src
BUILD_DIR = build

SRCS = $(shell find $(SRC_DIR) -name "*.c")
REL_SRCS = $(patsubst $(SRC_DIR)/%,%,$(SRCS))
OBJS = $(addprefix $(BUILD_DIR)/, $(REL_SRCS:.c=.o))
DEPS = $(OBJS:.o=.d)

all: main.hex

main.hex: main.elf
	$(OBJCOPY) -O ihex -R .eeprom $< $@

main.elf: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEPFLAGS) -c $< -o $@

-include $(DEPS)

flash: main.hex
	avrdude -c usbasp -p m32 -U flash:w:main.hex:i

clean:
	rm -rf $(BUILD_DIR) main.elf main.hex
